"""rating

Revision ID: b21d97b015b9
Revises: f6eda7049057
Create Date: 2022-03-03 19:43:53.923310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21d97b015b9'
down_revision = 'f6eda7049057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(None, 'author_model', ['surname'])
    op.add_column('quote_model', sa.Column('rate', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_model', 'rate')
    op.drop_constraint(None, 'author_model', type_='unique')
    # ### end Alembic commands ###
